import "./pixelmix.ttf";

component Button inherits Rectangle {
    callback focus-up() -> EventResult;
    callback focus-down() -> EventResult;
    callback focus-left() -> EventResult;
    callback focus-right() -> EventResult;
    callback pressed();

    in-out property text <=> txt.text;

    horizontal-stretch: 0;
    border-width: 1px;
    border-color: black;
    background: focus.has-focus ? #fff : #eee;
    height: txt.preferred-height + 6px;
    min-width: txt.preferred-width + 6px;
    txt := Text {
        x: (parent.width - self.width) / 2;
        y: (parent.height - self.height) / 2;
        color: #000;
    }

    focus := FocusScope {
        key-pressed(event) => {
            if (event.text == Key.Return) {
                pressed();
                accept
            } else if (event.text == Key.UpArrow) {
                focus-up()
            } else if (event.text == Key.DownArrow) {
                focus-down()
            } else if (event.text == Key.LeftArrow) {
                focus-left()
            } else if (event.text == Key.RightArrow) {
                focus-right()
            } else {
                parent.text = "Event: '\{event.text}'";
                accept
            }
        }
    }

    forward-focus: focus;
}

export component MyUI inherits Window {
    width: 240px;
    height: 160px;
    background: #E8E8E8;
    default-font-family: "pixelmix";
    default-font-size: 8px;

    property <int> counter: 0;

    forward-focus: btn_cart;
    focus-scope := FocusScope {
        key-pressed(event) => {
            debug(event);
            counter += 100;
            accept
        }

        VerticalLayout {
            alignment: start;
            height: 100%;
            padding: 8px;
            spacing: 8px;

            Image {
                source: @image-url("logo.png");
                height: 22px;
            }

            GridLayout {
                spacing: 4px;
                Row {
                    btn_cart := Button {
                        width: 50%;
                        height: 32px;
                        text: "Run Cartridge";
                        focus-right => {
                            btn_rom.focus();
                            accept
                        }
                        focus-down => {
                            btn_settings.focus();
                            accept
                        }
                    }

                    btn_rom := Button {
                        width: 50%;
                        height: 32px;
                        text: "Load ROM";
                        focus-left => {
                            btn_cart.focus();
                            accept
                        }
                        focus-down => {
                            btn_tools.focus();
                            accept
                        }
                    }
                }

                Row {
                    btn_settings := Button {
                        text: "Settings";
                        focus-up => {
                            btn_cart.focus();
                            accept
                        }
                        focus-right => {
                            btn_tools.focus();
                            accept
                        }
                    }

                    btn_tools := Button {
                        text: "Tools";
                        focus-up => {
                            btn_rom.focus();
                            accept
                        }
                        focus-left => {
                            btn_settings.focus();
                            accept
                        }
                    }
                }
            }

            Text {
                text: "Counter: " + counter;
                horizontal-alignment: center;
            }
        }
    }
}
