import "../fonts/pixelmix.ttf";
import { SettingEntry, SettingValue, SettingType } from "screens/settings/types.slint";

export enum ScreenId {
    MainMenu,
    RomSelect,
    Game,
    Settings,
}

export global Palette { }

export global Global {
    // Whether Home is currently pressed.
    in-out property <bool> home-pressed: false;
    // Whether the current pressing of Home was used for a shortcut key combo.
    in-out property <bool> home-consumed;
    out property <ScreenId> current-screen: MainMenu;
    in-out property <bool> ui-transparent: false;
    in-out property <bool> ui-status-bar: true;
    in-out property <bool> power-menu-visible: false;

    public function set-screen(screen: ScreenId){
        current-screen = screen;
        ui-transparent = (screen == ScreenId.Game);
        Backend.screen-enter(screen);
    }
}

export global Backend {
    in-out property <bool> volume-visible: false;
    in-out property <int> volume-level: 50;
    in property <int> volume-increment: 5;

    in-out property <bool> brightness-visible: false;
    in-out property <int> brightness-level: 50;
    in property <int> brightness-increment: 5;

    in property <int> battery-level: 11;
    in property <[string]> rom-select-list: ["a", "b", "c", "d", "e"];
    in property <[SettingEntry]> settings: [
        { name: "check 1", type: SettingType.checkbox, value: { bool-value: true } },
        { name: "check 2", type: SettingType.checkbox, value: { bool-value: false } },
        { name: "check 3", type: SettingType.checkbox, value: { bool-value: true } },
        { name: "subpage", type: SettingType.subpage },
        { name: "datetime", type: SettingType.datetime },
    ];

    callback volume-changed(int);
    callback brightness-changed(int);
    callback power-off();

    callback main-menu-run-cartridge();
    callback main-menu-load-rom();
    callback rom-select-selected(int) -> bool;
    callback game-set-paused(bool);
    callback game-reset();
    callback settings-updated(int, SettingValue);

    callback screen-enter(ScreenId);

    callback push-focus();
    callback pop-focus();
}
