import "../fonts/pixelmix.ttf";

export enum ScreenId {
    MainMenu,
    RomSelect,
    Game,
}

export global Palette { }

export global Global {
    in-out property <int> battery-level: 11;
    in property <[string]> rom-select-list: ["a", "b", "c", "d", "e"];

    out property <ScreenId> current-screen: MainMenu;
    in-out property <bool> ui-transparent: false;
    in-out property <bool> ui-status-bar: true;

    public function set-screen(screen: ScreenId){
        current-screen = screen;
        ui-transparent = (screen == ScreenId.Game);
    }
}

export global Backend {
    callback main-menu-run-cartridge();
    callback main-menu-load-rom();
    callback rom-select-selected(int) -> bool;
    callback game-set-paused(bool);
    callback game-reset();
}
