import { StatusBar } from "components/status_bar.slint";
import { TextListView } from "components/list_view.slint";
import { VolumeBar } from "components/volume_bar.slint";
import { RomSelectScreen } from "screens/rom_select.slint";
import { MainMenuScreen } from "screens/main_menu.slint";
import { GameScreen } from "screens/game.slint";
import { Global, ScreenId } from "common.slint";

export { Global, ScreenId }

export component MainWindow inherits Window {
    width: 240px;
    height: 160px;
    background: Global.ui-transparent ? transparent : #E8E8E8;
    default-font-family: "pixelmix";
    default-font-size: 8px;

    private property <int> counter: 0;
    private property <string> screen-title;

    status-bar := StatusBar {
        visible: Global.ui-status-bar;
        title: "\{root.screen-title} | \{counter}";
    }

    volume-bar := VolumeBar {
        x: 4px;
        y: parent.height * 0.25;
    }

    focus-scope := FocusScope {
        y: status-bar.height;
        height: parent.height - self.y;

        VerticalLayout {
            padding: 4px;
            Rectangle {
                if (Global.current-screen == ScreenId.MainMenu): MainMenuScreen {
                    init => {
                        self.focus();
                        root.screen-title = self.title;
                    }
                }

                if (Global.current-screen == ScreenId.RomSelect): RomSelectScreen {
                    init => {
                        self.focus();
                        root.screen-title = self.title;
                    }
                }

                if (Global.current-screen == ScreenId.Game): GameScreen {
                    init => {
                        Global.ui-status-bar = false;
                        self.focus();
                        root.screen-title = self.title;
                    }
                }
            }
        }

        key-pressed(event) => {
            if (event.text == "l" || event.text == "VolUp" || event.text == "VolDown") {
                volume-bar.show = true;
            }
            counter += 1;
            accept
        }
    }
}
