import { StatusBar } from "components/status_bar.slint";
import { TextListView } from "components/list_view.slint";
import { VolumeBar } from "components/volume_bar.slint";
import { RomSelectScreen } from "screens/rom_select.slint";
import { MainMenuScreen } from "screens/main_menu.slint";
import { GameScreen } from "screens/game.slint";
import { Properties, ScreenId } from "common.slint";

export { Properties, ScreenId }

export component MainWindow inherits Window {
    width: 240px;
    height: 160px;
    background: Properties.hide-ui ? transparent : #E8E8E8;
    default-font-family: "pixelmix";
    default-font-size: 8px;

    private property <int> counter: 0;
    private property <string> screen-title;

    status-bar := StatusBar {
        visible: !Properties.hide-ui;
        title: "\{root.screen-title} | \{counter}";
    }

    volume-bar := VolumeBar {
        x: 4px;
        y: parent.height * 0.25;
    }

    focus-scope := FocusScope {
        y: status-bar.height;
        height: parent.height - self.y;

        VerticalLayout {
            padding: 4px;
            Rectangle {
                if (Properties.current-screen == ScreenId.MainMenu): MainMenuScreen {
                    init => {
                        self.focus();
                        root.screen-title = self.title;
                    }
                }

                if (Properties.current-screen == ScreenId.RomSelect): RomSelectScreen {
                    init => {
                        self.focus();
                        root.screen-title = self.title;
                    }
                }

                if (Properties.current-screen == ScreenId.Game): GameScreen {
                    init => {
                        Properties.hide-ui = true;
                        self.focus();
                        root.screen-title = self.title;
                    }
                }
            }
        }

        key-pressed(event) => {
            if (event.text == "l") {
                volume-bar.show = !volume-bar.show;
            }
            counter += 1;
            accept
        }
    }
}
