import { Global, ScreenId, Backend } from "../common.slint";
import { ScreenBase } from "../components/screen.slint";
import { ScrollView } from "../components/scroll_view.slint";

export component AboutScreen inherits ScreenBase {
    title: "About";
    forward-focus: i-view;

    FocusScope {
        VerticalLayout {
            height: 100%;
            spacing: 2px;

            i-view := ScrollView {
                VerticalLayout {
                    spacing: 8px;
                    padding: 2px;
                    alignment: start;

                    Text {
                        horizontal-alignment: center;
                        text: "Game Bub\ngithub.com/elipsitz/gamebub";
                    }

                    Text {
                        horizontal-alignment: center;
                        text: "Serial: \{Backend.hardware-serial}\nHardware version: \{Backend.hardware-version}\nFirmware version: \{Backend.firmware-version}";
                    }
                }
            }

            HorizontalLayout {
                Text {
                    text: "B: Back";
                    horizontal-alignment: right;
                }
            }
        }

        key-pressed(event) => {
            if event.text == "Home" && !Global.home-consumed {
                Global.set-screen(ScreenId.MainMenu);
                accept
            } else if (event.text == "b") {
                Global.set-screen(ScreenId.Settings);
                accept
            } else {
                reject
            }
        }
    }
}
