import { Global, ScreenId, Backend } from "../common.slint";
import { ScreenBase } from "../components/screen.slint";
import { Button } from "../components/button.slint";

export component MainMenuScreen inherits ScreenBase {
    forward-focus: btn-cart;
    i-focus-scope := FocusScope {
        VerticalLayout {
            alignment: space-around;
            height: 100%;
            padding: 8px;
            spacing: 8px;

            Image {
                source: @image-url("../../logo.png");
                height: 32px;
                colorize: #3A3C99;
                image-rendering: pixelated;
            }

            VerticalLayout {
                spacing: 4px;

                HorizontalLayout {
                    spacing: 4px;

                    btn-cart := Button {
                        width: (parent.width - 4px) / 2;
                        height: 32px;
                        text: "Run Cartridge";
                        on-right => {
                            btn-rom.focus();
                            accept
                        }
                        on-down => {
                            btn-settings.focus();
                            accept
                        }
                        on-pressed => {
                            Backend.main-menu-run-cartridge();
                        }
                    }

                    btn-rom := Button {
                        width: (parent.width - 4px) / 2;
                        height: 32px;
                        text: "Load ROM";
                        on-left => {
                            btn-cart.focus();
                            accept
                        }
                        on-down => {
                            btn-about.focus();
                            accept
                        }
                        on-pressed => {
                            Global.set-screen(ScreenId.RomSelect);
                            Backend.main-menu-load-rom();
                        }
                    }
                }

                HorizontalLayout {
                    spacing: 4px;

                    btn-settings := Button {
                        text: "Settings";
                        width: (parent.width - 8px) / 3;
                        on-up => {
                            btn-cart.focus();
                            accept
                        }
                        on-right => {
                            btn-tools.focus();
                            accept
                        }
                        on-pressed => {
                            Global.set-screen(ScreenId.Settings);
                        }
                    }

                    btn-tools := Button {
                        text: "Tools";
                        width: (parent.width - 8px) / 3;
                        on-up => {
                            btn-rom.focus();
                            accept
                        }
                        on-left => {
                            btn-settings.focus();
                            accept
                        }
                        on-right => {
                            btn-about.focus();
                            accept
                        }
                        on-pressed => {
                            Global.set-screen(ScreenId.Tools);
                        }
                    }

                    btn-about := Button {
                        text: "About";
                        width: (parent.width - 8px) / 3;
                        on-up => {
                            btn-rom.focus();
                            accept
                        }
                        on-left => {
                            btn-tools.focus();
                            accept
                        }
                        on-pressed => {
                            Global.set-screen(ScreenId.About);
                        }
                    }
                }
            }
        }
    }
}
