import { Global, ScreenId, Backend } from "../common.slint";
import { ScreenBase } from "../components/screen.slint";
import { Button } from "../components/button.slint";

enum ButtonId {
    Cart,
    Rom,
    Settings,
    Tools,
}

global MainMenu {
    in-out property <ButtonId> last-focus: Cart;
}

export component MainMenuScreen inherits ScreenBase {

    forward-focus: i-focus-scope;
    i-focus-scope := FocusScope {
        focus-changed-event => {
            if (self.has-focus) {
                if (MainMenu.last-focus == ButtonId.Cart) {
                    btn-cart.focus();
                } else if (MainMenu.last-focus == ButtonId.Rom) {
                    btn-rom.focus();
                } else if (MainMenu.last-focus == ButtonId.Settings) {
                    btn-settings.focus();
                } else if (MainMenu.last-focus == ButtonId.Tools) {
                    btn-tools.focus();
                }
            }
        }

        Image {
            source: @image-url("../../logo.png");
            y: ((50% * parent.height) - self.height) / 2;
            height: 12px * (Global.window-height / 80px);
            image-rendering: pixelated;
            visible: !Global.ui-transparent;

            init => {
                debug("logo y:", self.absolute-position.y);
            }
        }

        VerticalLayout {
            y: 50% * parent.height;
            height: 50%;
            padding: 8px;
            spacing: 4px;

            HorizontalLayout {
                spacing: 4px;

                btn-cart := Button {
                    width: (parent.width - 4px) / 2;
                    height: 25% * root.height;
                    text: "Run Cartridge";
                    on-right => {
                        if Backend.sdcard-mounted {
                            btn-rom.focus();
                        }
                        accept
                    }
                    on-down => {
                        btn-settings.focus();
                        MainMenu.last-focus = ButtonId.Cart;
                        accept
                    }
                    on-pressed => {
                        MainMenu.last-focus = ButtonId.Cart;
                        Backend.main-menu-run-cartridge();
                    }
                }

                btn-rom := Button {
                    width: (parent.width - 4px) / 2;
                    height: 25% * root.height;
                    text: Backend.sdcard-mounted ? "Load ROM" : "No microSD card";
                    disabled: !Backend.sdcard-mounted;
                    on-left => {
                        btn-cart.focus();
                        accept
                    }
                    on-down => {
                        btn-tools.focus();
                        MainMenu.last-focus = ButtonId.Rom;
                        accept
                    }
                    on-pressed => {
                        MainMenu.last-focus = ButtonId.Rom;
                        Global.set-screen(ScreenId.RomSelect);
                        Backend.main-menu-load-rom();
                    }
                }
            }

            HorizontalLayout {
                spacing: 4px;

                btn-settings := Button {
                    text: "Settings";
                    width: (parent.width - 4px) / 2;
                    height: 15% * root.height;
                    on-up => {
                        btn-cart.focus();
                        MainMenu.last-focus = ButtonId.Settings;
                        accept
                    }
                    on-right => {
                        btn-tools.focus();
                        accept
                    }
                    on-pressed => {
                        MainMenu.last-focus = ButtonId.Settings;
                        Global.set-screen(ScreenId.Settings);
                    }
                }

                btn-tools := Button {
                    text: "Tools";
                    width: (parent.width - 4px) / 2;
                    height: 15% * root.height;
                    on-up => {
                        if Backend.sdcard-mounted {
                            btn-rom.focus();
                        }
                        MainMenu.last-focus = ButtonId.Tools;
                        accept
                    }
                    on-left => {
                        btn-settings.focus();
                        accept
                    }
                    on-pressed => {
                        MainMenu.last-focus = ButtonId.Tools;
                        Global.set-screen(ScreenId.Tools);
                    }
                }
            }
        }
    }
}
