import { Global, ScreenId, Backend } from "../common.slint";
import { ScreenBase } from "../components/screen.slint";
import { TextListView } from "../components/list_view.slint";

export component RomSelectScreen inherits ScreenBase {
    in property <[string]> files;
    private property <bool> is-loading: false;

    title: "Load ROM...";
    forward-focus: list;

    files: Backend.rom-select-list;
    i-focus-scope := FocusScope {
        key-pressed(event) => {
            if (Backend.rom-select-is-loading) {
                accept
            } else if event.text == "Home" && !Global.home-consumed {
                Global.set-screen(ScreenId.MainMenu);
                accept
            } else if (event.text == "b" && !event.repeat) {
                Backend.rom-select-is-loading = Backend.rom-select-up();
                accept
            } else {
                reject
            }
        }
        VerticalLayout {
            height: 100%;
            spacing: 2px;

            Text {
                text: Backend.rom-select-path;
            }

            list := TextListView {
                model: root.files;
                wrap: true;
                disabled: Backend.rom-select-is-loading;
                focus-item <=> Backend.rom-select-index;
                init => {
                    self.fix-focus-item();
                }
                on-item-selected(i) => {
                    Backend.rom-select-is-loading = Backend.rom-select-selected(i);
                }
                on-item-focused(i) => {
                    Backend.rom-select-focused(i);
                }
            }

            HorizontalLayout {
                Text {
                    text: "A: Select";
                    horizontal-alignment: left;
                }

                Text {
                    text: "Home: Back";
                    horizontal-alignment: center;
                }

                Text {
                    text: "B: Up";
                    horizontal-alignment: right;
                }
            }
        }
    }

    if Backend.rom-select-is-loading:  Rectangle {
        background: #FFF;
        border-color: black;
        border-width: 1px;
        width: i-layout.min-width;
        height: i-layout.min-height;

        i-layout := VerticalLayout {
            padding: 8px;
            spacing: 4px;
            i-text := Text {
                horizontal-alignment: center;
                text: "Loading...";
            }

            Rectangle {
                background: black;
                width: Backend.rom-select-progress * i-text.min-width;
                height: 2px;
            }
        }
    }
}
