import { Properties, ScreenId } from "../common.slint";
import { ScreenBase } from "../components/screen.slint";
import { TextListView } from "../components/list_view.slint";

export component RomSelectScreen inherits ScreenBase {
    in property <[string]> files;
    callback on-selected(int);

    title: "Load ROM...";
    forward-focus: list;

    files: [
        "Parent directory",
        "item a",
        "item b",
        "item c",
        "item d",
        "item e",
        "item f",
        "item g",
        "item h",
        "item i",
        "item k",
        "item l",
        "item m",
    ];
    i-focus-scope := FocusScope {
        key-pressed(event) => {
            if (event.text == "b") {
                Properties.set-screen(ScreenId.MainMenu);
                accept
            } else {
                reject
            }
        }

        VerticalLayout {
            height: 100%;
            list := TextListView {
                model: root.files;
                wrap: true;
                on-item-selected(i) => {
                    root.on-selected(i)
                }
            }

            HorizontalLayout {
                Text {
                    text: "A: Select";
                }

                Text {
                    text: "B: Cancel";
                    horizontal-alignment: right;
                }
            }
        }
    }
}
