import { Global, ScreenId, Backend } from "../common.slint";
import { ScreenBase } from "../components/screen.slint";
import { Button } from "../components/button.slint";
import { ControlHint } from "../components/control_hint.slint";

component ControlsPage inherits Rectangle {
    in property <int> step;
    private property <color> highlight: #761C92;

    private property <int> tick: 0;
    private property <bool> anim: mod(tick, 5) < 3;

    Timer {
        interval: 0.2s;
        triggered => {
            tick = mod(tick + 1, 10);
        }
    }

    Image {
        source: @image-url("../../device.png");
        x: (50% * root.width) - (self.width / 2);
        y: (50% * root.height) - (self.height / 2);
        // width: 198px * 1.5;
        image-rendering: pixelated;
        colorize: black;

        if step == 0: Rectangle {
            background: highlight;
            width: 8px;
            height: 8px;
            x: 181px;
            y: 30px;
            border-radius: 3px;
            visible: anim;
        }

        if step == 1: Rectangle {
            background: highlight;
            width: 8px;
            height: 8px;
            x: 173px;
            y: 38px;
            border-radius: 3px;
            visible: anim;
        }

        if step == 2: Rectangle {
            background: highlight;
            width: 4px;
            height: 2px;
            x: 135px;
            y: 1px;
            visible: anim;
        }

        if step == 3 || step == 5: Rectangle {
            background: highlight;
            width: 5px;
            height: 5px;
            x: 29px;
            y: 68px;
            border-radius: 3px;
            visible: step == 5 || anim;
        }
        if step == 4 || step == 5: Rectangle {
            Rectangle {
                background: highlight;
                width: 6px;
                height: 2px;
                x: 145px;
                y: 1px;
                visible: tick >= 0 && tick < 4;
            }

            Rectangle {
                background: highlight;
                width: 6px;
                height: 2px;
                x: 155px;
                y: 1px;
                visible: tick >= 5 && tick < 9;
            }
        }
    }

    Image {
        source: @image-url("../../logo.png");
        x: (50% * root.width) - (self.width / 2);
        y: (50% * root.height) - (self.height / 2);
        // height: 12px * 1.5;
        image-rendering: pixelated;
    }

    Rectangle {
        y: 24px;
        height: self.min-height;

        if step == 0: Text {
            text: "Press to Confirm";
        }

        if step == 1: Text {
            text: "Press to go Back";
        }

        if step == 2: Text {
            text: "Press to open Power menu";
        }

        if step == 3: Text {
            text: "Press to go Home";
        }

        if step == 4: Text {
            text: "Press to adjust volume";
        }

        if step == 5: Text {
            text: "Press Home + Volume to adjust brightness";
        }
    }

    ControlHint {
        label: "Continue";
        button: "a";
        x: root.width - self.width - 8px;
        y: root.height - self.height - 8px;
    }
}

export component SetupScreen inherits ScreenBase {
    private property <int> page: 0;

    function prev-page() {
        if (page > 0) {
            page -= 1;
        }
        if (page == 0) {
            Global.ui-transparent = true;
        }
    }

    function next-page() {
        Global.ui-transparent = false;
        page += 1;
        if (page == 9) {
            Backend.setup-complete();
            Global.set-screen(ScreenId.MainMenu);
        }
    }

    forward-focus: i-focus-scope;
    i-focus-scope := FocusScope {
        // Page 0: Logo
        if page == 0: Rectangle {
            ControlHint {
                label: "Begin Tutorial";
                button: "a";
                y: root.height - self.height - 8px;
            }
        }

        // Page 1: Controls
        if page >= 1 && page < 7: ControlsPage {
            step: page - 1;
        }

        // Docs and Update information
        if page == 7: Rectangle {
            init => {
                root.focus();
            }
            Text {
                text: "Read the full user guide at";
                horizontal-alignment: center;
                y: 50px;
            }

            Text {
                text: "docs.gamebub.net";
                horizontal-alignment: center;
                y: 66px;
                font-weight: 800;
            }

            Text {
                text: "Check for software updates at";
                horizontal-alignment: center;
                y: 120px;
            }

            Text {
                text: "update.gamebub.net";
                horizontal-alignment: center;
                y: 136px;
                font-weight: 800;
            }

            ControlHint {
                label: "Continue";
                button: "a";
                y: root.height - self.height - 8px;
            }
        }

        // Legal information
        if page == 8: Rectangle {
            Text {
                text: "Legal Information\n\nTODO";
                y: 12px;
            }

            ControlHint {
                label: "Continue";
                button: "a";
                y: root.height - self.height - 8px;
            }
        }

        key-pressed(event) => {
            if (event.repeat) {
                reject
            } else if (event.text == "a") {
                next-page();
                accept
            } else if (event.text == "b") {
                prev-page();
                accept
            } else {
                reject
            }
        }
    }
}
