import { Global, ScreenId, Backend, BatteryInfo } from "../../common.slint";
import { ScreenBase } from "../../components/screen.slint";
import { TextListView } from "../../components/list_view.slint";

export component ToolsScreen inherits ScreenBase {
    in property <[string]> tools: ["Mount SD Card over USB", "Cartridge backup / restore", "Debug battery info"];
    private property <int> selected-tool: -1;

    title: "Tools";
    forward-focus: i-focus-scope;

    i-focus-scope := FocusScope {
        key-pressed(event) => {
            if (event.text == "b") {
                if selected-tool == -1 {
                    Global.set-screen(ScreenId.MainMenu);
                }
                selected-tool = -1;
                accept
            } else {
                reject
            }
        }

        if selected-tool == -1: VerticalLayout {
            height: 100%;
            spacing: 2px;

            init => {
                list.focus();
            }

            list := TextListView {
                model: root.tools;
                wrap: true;
                on-item-selected(i) => {
                    debug("on-item-selected ", i);
                    root.selected-tool = i;
                }
            }

            HorizontalLayout {
                Text {
                    text: "A: Select";
                }

                Text {
                    text: "B: Back";
                    horizontal-alignment: right;
                }
            }
        }

        // Mount SD card over USB
        if selected-tool == 0: FocusScope {
            init => {
                self.focus();
                if Backend.sdcard-mounted {
                    Backend.tools-start-usb-drive();
                }
            }
            key-pressed(event) => {
                if (event.text == "Start") {
                    Backend.tools-end-usb-drive();
                }
                accept
            }
            VerticalLayout {
                alignment: center;
                spacing: 16px;

                if Backend.sdcard-mounted: Text {
                    horizontal-alignment: center;
                    text: "Exposing SD card as USB drive";
                }

                if !Backend.sdcard-mounted: Text {
                    horizontal-alignment: center;
                    text: "Error: no SD card mounted";
                }

                Text {
                    horizontal-alignment: center;
                    text: "Press START to reboot";
                }
            }
        }

        // Cartridge backup / restore
        if selected-tool == 1: FocusScope {
            init => {
                self.focus();
                Backend.tools-start-cart-reader();
            }
            key-pressed(event) => {
                if (event.text == "Start") {
                    Backend.tools-end-cart-reader();
                }
                accept
            }
            VerticalLayout {
                alignment: center;
                spacing: 16px;

                Text {
                    horizontal-alignment: center;
                    text: "Cartridge Backup / Restore";
                }

                Text {
                    horizontal-alignment: center;
                    text: "Press START to reboot";
                }
            }
        }

        // Debug battery info
        if selected-tool == 2: FocusScope {
            private property <BatteryInfo> info;
            init => {
                self.focus();
            }

            VerticalLayout {
                alignment: center;
                spacing: 16px;
                Text {
                    horizontal-alignment: center;
                    text: "Battery Info";
                }

                Text {
                    horizontal-alignment: center;
                    text: ("Charging: \{info.is-charging ? "yes" : "no"}\n" + //
                    "VBUS good: \{info.vbus-pgood ? "yes" : "no"}\n" + //
                    "Voltage: \{round(info.voltage * 100) / 100} V\n" + //
                    "Charge Level: \{round(info.level * 10) / 10}%\n" + //
                    "Charge Rate: \{round(info.charge-rate * 100) / 100} %/hr" //
                );
                }

                Text {
                    horizontal-alignment: center;
                    text: "B: Back";
                }

                Timer {
                    interval: 2s;
                    triggered => {
                        info = Backend.tools-get-battery-info();
                    }
                }
            }
        }
    }
}
