import { Global, ScreenId, Backend, BatteryInfo } from "../../common.slint";
import { ScreenBase } from "../../components/screen.slint";
import { TextListView } from "../../components/list_view.slint";
import { ControlHint } from "../../components/control_hint.slint";

export component ToolsScreen inherits ScreenBase {
    in property <[string]> tools: [
        "Mount SD Card over USB",
        "FlashGBX Cartridge Backup / Restore",
        "Debug battery info"
    ];
    private property <int> selected-tool: -1;

    title: "Tools";
    forward-focus: i-focus-scope;

    i-focus-scope := FocusScope {
        key-pressed(event) => {
            if (event.text == "b") {
                if selected-tool == -1 {
                    Global.set-screen(ScreenId.MainMenu);
                }
                selected-tool = -1;
                accept
            } else {
                reject
            }
        }

        if selected-tool == -1: VerticalLayout {
            height: 100%;
            spacing: 2px;

            init => {
                list.focus();
            }

            list := TextListView {
                model: root.tools;
                wrap: true;
                on-item-selected(i) => {
                    debug("on-item-selected ", i);
                    root.selected-tool = i;
                }
            }

            HorizontalLayout {
                alignment: space-between;

                ControlHint {
                    label: "Back";
                    button: "b";
                }

                ControlHint {
                    label: "Select";
                    button: "a";
                }
            }
        }

        // Mount SD card over USB
        if selected-tool == 0: FocusScope {
            init => {
                self.focus();
                if Backend.sdcard-mounted {
                    Backend.tools-start-usb-drive();
                }
            }
            key-pressed(event) => {
                if (event.text == "Home") {
                    Backend.tools-end-usb-drive();
                }
                accept
            }

            if Backend.sdcard-mounted: Text {
                horizontal-alignment: center;
                text: "Now exposing the SD card as USB drive";
            }

            if !Backend.sdcard-mounted: Text {
                horizontal-alignment: center;
                text: "Error: no SD card mounted";
            }

            ControlHint {
                label: "Exit";
                button: "home";
                y: root.height - self.height - 8px;
            }
        }

        // Cartridge backup / restore
        if selected-tool == 1: FocusScope {
            init => {
                self.focus();
                Backend.tools-start-cart-reader();
            }
            key-pressed(event) => {
                if (event.text == "Home") {
                    Backend.tools-end-cart-reader();
                }
                accept
            }
            Text {
                horizontal-alignment: center;
                text: "Cartridge Backup and Restore Mode\n\nConnect Game Bub to a computer running FlashGBX\nSee the User Guide for more information";
            }

            ControlHint {
                label: "Exit";
                button: "home";
                y: root.height - self.height - 8px;
            }
        }

        // Debug battery info
        if selected-tool == 2: FocusScope {
            private property <BatteryInfo> info;
            init => {
                self.focus();
            }

            VerticalLayout {
                alignment: center;
                spacing: 16px;
                Text {
                    horizontal-alignment: center;
                    text: "Battery Info";
                }

                Text {
                    horizontal-alignment: center;
                    text: ("Charging: \{info.is-charging ? "yes" : "no"}\n" + //
                        "VBUS good: \{info.vbus-pgood ? "yes" : "no"}\n" + //
                        "Voltage: \{info.voltage.to-fixed(2)} V\n" + //
                        "Charge Level: \{info.level.to_fixed(2)}%\n" + //
                        "Current: \{info.current.to-fixed(3)} A\n" //
                    );
                }
            }

            ControlHint {
                label: "Back";
                button: "b";
                y: root.height - self.height - 8px;
            }

            Timer {
                interval: 2s;
                triggered => {
                    info = Backend.tools-get-battery-info();
                }
            }
        }
    }
}
