export component ListViewBase inherits Rectangle {
    in property <int> num-items;
    in property <bool> wrap: false;
    out property <int> focus-item: 0;
    in-out property <bool> item-selected: false;

    private property <bool> has-scrollbar: area.viewport-height > area.height;
    private property <length> scrollbar-width: 2px;
    private property <length> item-height: area.viewport-height / self.num-items;
    private property <int> into-view-item: 0;
    private property <length> into-view-item-y: root.item-y(root.into-view-item);
    private property <bool> has-focus;

    callback on-focus-item-changed(/* focus-item */ int);
    callback on-item-selected(/* selected-item */ int);

    public function set-focus-item(index: int){
        if (!wrap && (index < 0 || index >= num-items)) {
            return;
        }
        root.unselect();
        focus-item = mod(num-items + index, num-items);
        bring-into-view(focus-item);
    }

    pure function first-visible-item() -> int {
        return min(root.num-items - 1, max(0, round(-area.viewport-y / root.item-height)));
    }

    pure function item-y(index: int) -> length {
        return area.viewport-y + index * root.item-height;
    }

    function bring-into-view(index: int){
        if (index < 0 || index >= num-items) {
            return;
        }
        into-view-item = index;

        if (into-view-item-y < 0) {
            area.viewport-y += 0 - into-view-item-y;
        }
        if (into-view-item-y + item-height > area.height) {
            area.viewport-y -= into-view-item-y + item-height - area.height;
        }
    }

    protected function focus-up(){
        root.set-focus-item(root.focus-item - 1);
    }

    protected function focus-down(){
        root.set-focus-item(root.focus-item + 1);
    }

    protected function select-focus-item(){
        root.item-selected = true;
        root.on-item-selected(root.focus-item);
    }

    protected function unselect(){
        root.item-selected = false;
        root.focus();
    }

    forward-focus: i-focus-scope;
    border-width: 1px;
    border-color: black;

    i-focus-scope := FocusScope {
        area := Flickable {
            x: 2px;
            y: 2px;
            width: root.has-scrollbar ? scroll-bar.x - scrollbar-width - 1px : parent.width - 4px;
            height: parent.height - 4px;
            VerticalLayout {
                alignment: start;
                @children
            }
        }

        focus-changed-event => {
            root.has-focus = self.has-focus;
        }

        key-pressed(event) => {
            if (event.text == Key.UpArrow) {
                root.focus-up();
                return accept;
            } else if (event.text == Key.DownArrow) {
                root.focus-down();
                return accept;
            } else if (event.text == "a" && !event.repeat) {
                if root.item-selected {
                    root.unselect();
                } else {
                    root.select-focus-item();
                }
                return accept;
            } else if (event.text == "b" && root.item-selected && !event.repeat) {
                root.unselect();
                return accept;
            }
            reject
        }
    }

    scroll-bar := Rectangle {
        visible: has-scrollbar;
        x: parent.width - self.width - 2px;
        y: 2px;
        width: scrollbar-width;
        height: parent.height - 4px;
        inner := Rectangle {
            y: (-area.viewport-y / area.viewport-height) * parent.height;
            width: 100%;
            height: (area.height / area.viewport-height) * parent.height;
            background: black;
        }
    }
}

component TextListItem {
    in property <string> text;
    in property <bool> highlighted;
    in property <int> index;

    min-width: i-text.min-width;
    min-height: i-text.min-height + 2px;
    vertical-stretch: 0;
    horizontal-stretch: 1;

    i-background := Rectangle {
        background: root.highlighted ? #bbb : transparent;
        width: root.width;
        i-text := Text {
            x: 2px;
            text: root.text;
            vertical-alignment: center;
            horizontal-alignment: left;
            overflow: elide;
        }
    }

    @children
}

export component TextListView inherits ListViewBase {
    in property <[string]> model;
    num-items: model.length;

    for item[index] in root.model: child-items := TextListItem {
        index: index;
        text: item;
        highlighted: index == root.focus-item;
        height: self.min-height;
    }
}
