import { Properties } from "../common.slint";

export component StatusBar inherits Rectangle {
    in property <string> title;

    x: 0;
    y: 0;
    width: 100%;
    height: 14px;
    background: #ccc;

    title-text := Text {
        text: root.title;
        horizontal-alignment: left;
        x: 4px;
    }

    battery-text := Text {
        text: "\{Properties.battery-level}%";
        horizontal-alignment: right;
        x: parent.width - self.width - 4px;
    }
}
