import { Global, Backend } from "../common.slint";

export component VolumeBar inherits Rectangle {
    width: 16px;
    visible: Backend.volume-show;

    Rectangle {
        background: gray;
        width: 100%;
        height: parent.height * (Backend.volume-level * 1%);
        y: parent.height - self.height;
        border-radius: 4px;
    }

    Rectangle {
        border-color: black;
        border-width: 1px;
        border-radius: 4px;
    }
}
